version: "3"
services:
  backend:
    build:
      context: .
    ports:
      - "4000"
    restart: always
    depends_on:
      - db
  frontend:
    build:
      context: ./client
    ports:
      - "80"
    depends_on:
      - backend
  db:
    image: mariadb:10.8-jammy
    expose:
      - "3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  caddy:
    build:
      context: ./dev
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
