version: "3"
services:
  backend:
    build:
      context: .
    ports:
      - "4000:4000"
      - "5555:5555"
      - "7000:7000"
    restart: always
    environment:
      MARIADB_HOST: db
      MARIADB_USERNAME: isucon
      MARIADB_PASSWORD: isucon
      MARIADB_DATABASE: isucon
      MARIADB_PORT: 3306
      ENV: dev
    depends_on:
      - db
    volumes:
      - /home/isucon/isuumo:/home/isucon/isuumo
  frontend:
    build:
      context: ./client
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - backend
  db:
    image: mariadb:latest
    expose:
      - "3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
volumes:
  db:
