version: "3"
services:
  backend:
    build:
      context: .
    container_name: piscon-portal-backend
    ports:
      - "4000:4000"
      - "5555:5555"
      - "7000:7000"
    restart: always
    depends_on:
      - db
    volumes:
      - /home/isucon/isucari:/isucari  # ベンチマーカーを置くディレクトリ
      - /etc/ssl/certs:/etc/ssl/certs
    environment:
      TZ: Asia/Tokyo
    sysctls:
      # Tune up network
      net.core.somaxconn: 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 10
    env_file: .env
  frontend:
    build:
      context: ./client
    container_name: piscon-portal-frontend
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    volumes:
      - /var/log/caddy:/var/log/caddy
      - ./client/caddy/Caddyfile-prod:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    env_file: .env
  db:
    image: mariadb:10.8-jammy
    container_name: piscon-portal-db
    expose:
      - "3306"
    command: mysqld --default-time-zone=Asia/Tokyo
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      TZ: Asia/Tokyo
    env_file: .env
volumes:
  db:
  caddy-data:
    external: true
  caddy-config:
