version: "3"
services:
  backend:
    build:
      context: .
    tty: true
    ports:
      - "4000"
    restart: always
    command: ./piscon_portal
    environment:
      MARIADB_HOST: db
      MARIADB_USERNAME: isucon
      MARIADB_PASSWORD: isucon
      MARIADB_DATABASE: isucon
      MARIADB_PORT: 3306
      ENV: dev
    depends_on:
      - db
  frontend:
    build:
      context: ./client
    tty: true
    ports:
      - "80"
    depends_on:
      - backend
  db:
    image: mariadb:10.8-jammy
    expose:
      - "3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  caddy:
    build:
      context: ./dev
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
